### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by JLHwung**

### CODE REVIEW

**Comment by knksmith57** [comment]
@JLHwung I've added + enabled travis for this repo. Should be good to land this!

Let me know if it gives you any trouble. Thanks!

**Comment by knksmith57** [comment]
--> https://travis-ci.org/knksmith57/hexo-renderer-sass

**Comment by knksmith57** [comment]
Also, on a related note, I've enabled coveralls --> https://coveralls.io/github/knksmith57/hexo-renderer-sass

**Comment by JLHwung** [comment]
@knksmith57 Thank you so much.

**Pull request merged**
