### PR TITLE
fix: add engine requirements for node >= 0.10

### PR DESCRIPTION
**Pull request by knksmith57**

### CODE REVIEW

**Comment by knksmith57** [comment]
OK, I was thinking we'd land this _before_ #25. Probably can just close this out without landing then, @JLHwung?

**Comment by JLHwung** [comment]
@knksmith57 Actually I think this PR could be landed. I have pushed a branch `0.2.x`, could you rebase on that branch and release `0.2.1`? Then we can move forward to 0.3.

**Comment by knksmith57** [comment]
@JLHwung alrighty, changed the target branch to `0.2.x`, rebased clean. The build is failing because there's no config on the `0.2.x` branch, but I think we're good to go.

Want me to cut the `0.2.1` release now?

**Comment by JLHwung** [comment]
@knksmith57 Thank you for rebasing. Looks good to me. 😄

**Pull request merged**
