### PR TITLE
Migrate to GitHub Actions and drop Node < 14 support

### LINKED ISSUE #49: get CI working again, move from Travis to something else (eg: GitHub Actions)
Building on travis-ci.org is no longer supported. also the build configuration in here is targeting completed EOL Node.js versions and needs to be updated to be useful.

* [ ] migrate off of Travis to something else, probably GitHub Actions
* [ ] drop builds for EOL Node.js versions and target Node.js 14 + 16 + 18 (12 goes EOL _tomorrow_ and 18 will go LTS in October)
* [ ] nuke all the old LibSass system deps that aren't needed anymore (or are they?)

### PR DESCRIPTION
**Pull request by JLHwung**
Closes #49

The new GitHub actions runs lint & coverage report on the latest Node, then runs only test on other Node versions.

### CODE REVIEW

**Comment by JLHwung** [comment]
@knksmith57 Hey there. The codecov upload actions requires `secrets.CODECOV_TOKEN` to be set. Can you generate one and put it there? For reference you can see

https://docs.codecov.com/docs/quick-start and 
https://docs.github.com/en/actions/security-guides/encrypted-secrets

Thank you.

**Comment by knksmith57** [comment]
Heya @JLHwung, I followed that guide and used the GitHub App installation method that they recommend instead of the environment variable approach—it's installed on this repo now and I verified that Codecov has it registered now and is showing "no data"
image

If that doesn't work, please let me know and I can also generate a secret for it! Thank you!

**Comment by JLHwung** [comment]
@knksmith57 It works now, thanks!
https://github.com/knksmith57/hexo-renderer-sass/actions/runs/5280453565/jobs/9553535964#step:7:35

**Comment by knksmith57** [comment]
> @knksmith57 It works now, thanks! https://github.com/knksmith57/hexo-renderer-sass/actions/runs/5280453565/jobs/9553535964#step:7:35

heck yeah, nice!! 😄 🎉

Thanks so much for getting this project back in shape and wiring all that up!

**Pull request merged**
